// This file #includes all OCCUtils implementation .cc files. The
// purpose is to allow a user to build OCCUtils by compiling this
// file alone.

// The following lines pull in the real occutils*.cc files.
#include "occutils-axis.cc"
#include "occutils-boolean.cc"
#include "occutils-bounding-box.cc"
#include "occutils-compound.cc"
#include "occutils-curve.cc"
#include "occutils-direction.cc"
#include "occutils-edge.cc"
#include "occutils-equality.cc"
#include "occutils-face.cc"
#include "occutils-fillet.cc"
#include "occutils-io.cc"
#include "occutils-ldom.cc"
#include "occutils-line.cc"
#include "occutils-pipe.cc"
#include "occutils-plane.cc"
#include "occutils-point.cc"
#include "occutils-primitive.cc"
#include "occutils-print-occ.cc"
#include "occutils-shape-components.cc"
#include "occutils-shape.cc"
#include "occutils-step-export.cc"
#include "occutils-surface.cc"
#include "occutils-wire.cc"
#include "xde/occutils-xde-app.cc"
#include "xde/occutils-xde-doc.cc"
